"""empty message

Revision ID: 96cdc807c0bd
Revises: 
Create Date: 2019-07-27 18:56:46.548474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96cdc807c0bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorization_email_id'), 'authorization', ['email_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('First_Name', sa.String(length=100), nullable=False),
    sa.Column('Last_Name', sa.String(length=100), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Height', sa.Integer(), nullable=True),
    sa.Column('Marital_Status', sa.Enum('NeverMarried', 'Divorced', 'AwaitingDivorce', 'Widowed', 'Didnt_Matter', name='marital_status'), nullable=True),
    sa.Column('Education', sa.String(length=300), nullable=True),
    sa.Column('Profession', sa.String(length=300), nullable=True),
    sa.Column('Religion', sa.Enum('Christian', 'Muslim', 'Hindu', 'Sikh', 'Buddhist', 'Jain', 'Didnt_Matter', name='religion'), nullable=True),
    sa.Column('Language', sa.Enum('Urdu', 'Hindi', 'Marathi', 'Punjabi', 'Sindhi', 'Kashmiri', 'Gujarati', 'Malayalam', 'Tamil', 'Assamese', 'Bengali', 'Kannada', 'Nepali', 'Telugu', 'Tulu', 'Odia', 'English', 'Konkani', 'Didnt_Matter', name='language'), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('Country', sa.Enum('Pakistan', 'India', 'USA', 'Australia', 'Bangladesh', 'Canada', 'Indonesia', 'Kuwait', 'SouthAfrica', 'UnitedArabEmirates', 'UnitedKingdom', 'Didnt_Matter', name='country'), nullable=True),
    sa.Column('Food', sa.Enum('Eggetarian', 'Vegetarian', 'Non_Vegetarian', 'OccasionallyNon_Vegetarian', 'Didnt_Matter', name='food'), nullable=True),
    sa.Column('Drinks', sa.Enum('DoesntDrink', 'DrinksOccasionally', 'DrinksOften', 'Didnt_Matter', name='drinks'), nullable=True),
    sa.Column('Smokes', sa.Enum('DoesntSmoke', 'SmokesOften', 'SmokesOccasionally', 'Didnt_Matter', name='smokes'), nullable=True),
    sa.Column('Skin_Tone', sa.Enum('WeatishskinTone', 'Fairskinned', 'Darkskinned', 'VeryFairskinned', 'Didnt_Matter', name='skin_tone'), nullable=True),
    sa.Column('Build', sa.Enum('AverageBuild', 'AthleticBuild', 'HeavyBuild', 'SlimBuild', 'Didnt_Matter', name='build'), nullable=True),
    sa.Column('Gender', sa.Enum('Male', 'Female', name='gender'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['authorization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user__prefrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Marital_Status', sa.Enum('NeverMarried', 'Divorced', 'AwaitingDivorce', 'Widowed', 'Didnt_Matter', name='marital_status'), nullable=True),
    sa.Column('Religion', sa.Enum('Christian', 'Muslim', 'Hindu', 'Sikh', 'Buddhist', 'Jain', 'Didnt_Matter', name='religion'), nullable=True),
    sa.Column('Language', sa.Enum('Urdu', 'Hindi', 'Marathi', 'Punjabi', 'Sindhi', 'Kashmiri', 'Gujarati', 'Malayalam', 'Tamil', 'Assamese', 'Bengali', 'Kannada', 'Nepali', 'Telugu', 'Tulu', 'Odia', 'English', 'Konkani', 'Didnt_Matter', name='language'), nullable=True),
    sa.Column('Country', sa.Enum('Pakistan', 'India', 'USA', 'Australia', 'Bangladesh', 'Canada', 'Indonesia', 'Kuwait', 'SouthAfrica', 'UnitedArabEmirates', 'UnitedKingdom', 'Didnt_Matter', name='country'), nullable=True),
    sa.Column('Food', sa.Enum('Eggetarian', 'Vegetarian', 'Non_Vegetarian', 'OccasionallyNon_Vegetarian', 'Didnt_Matter', name='food'), nullable=True),
    sa.Column('Drinks', sa.Enum('DoesntDrink', 'DrinksOccasionally', 'DrinksOften', 'Didnt_Matter', name='drinks'), nullable=True),
    sa.Column('Smokes', sa.Enum('DoesntSmoke', 'SmokesOften', 'SmokesOccasionally', 'Didnt_Matter', name='smokes'), nullable=True),
    sa.Column('Skin_Tone', sa.Enum('WeatishskinTone', 'Fairskinned', 'Darkskinned', 'VeryFairskinned', 'Didnt_Matter', name='skin_tone'), nullable=True),
    sa.Column('Build', sa.Enum('AverageBuild', 'AthleticBuild', 'HeavyBuild', 'SlimBuild', 'Didnt_Matter', name='build'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__prefrences')
    op.drop_table('users')
    op.drop_index(op.f('ix_authorization_email_id'), table_name='authorization')
    op.drop_table('authorization')
    # ### end Alembic commands ###
